import{a as L,S as q,i}from"./assets/vendor-CZY24G29.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const d of r.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function c(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=c(e);fetch(e.href,r)}})();const v="48848335-f5abf64d59c2aabc1155fb6ba",S="https://pixabay.com/api/";async function y(o,t=1,c=40){try{return(await L.get(S,{params:{key:v,q:o,Image_type:"photo",orientation:"horisontal",safesearch:!0,page:t,per_page:c}})).data}catch(s){console.error("Sorry, there are no images matching your search query. Please try again!",s)}}function m(o){return o.map(({webformatURL:t,largeImageURL:c,tags:s,likes:e,views:r,comments:d,downloads:w})=>`<div class="photo-card">
                    <a href="${c}" class="gallery-link">
                        <img src="${t}" alt="${s}" loading="lazy" />
                    </a>
                    <div class="info">
                        <p><strong>Likes:</strong> ${e}</p>
                        <p><strong>Views:</strong> ${r}</p>
                        <p><strong>Comments:</strong> ${d}</p>
                        <p><strong>Downloads:</strong> ${w}</p>
                    </div>
                </div>`).join("")}const p=document.querySelector("#search-form"),g=document.querySelector(".gallery"),n=document.querySelector(".load-more"),a=document.querySelector(".loader");let u="",l=1;const h=40;let f=0,b=new q(".gallery a");n.hidden=!0;a.hidden=!0;p.addEventListener("submit",async o=>{if(o.preventDefault(),u=o.target.elements.searchQuery.value.trim(),!u){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}l=1,g.innerHTML="",n.hidden=!0,a.hidden=!1;try{n.hidden=!1;const t=await y(u,l,h);if(f=t.totalHits,t.hits.length===0){i.info({title:"Info",message:"No results found. Try another search query!",position:"topRight"});return}g.innerHTML=m(t.hits),b.refresh(),p.reset(),t.hits.length<h||l*h>=f?i.info({title:"End or collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):n.hidden=!1}catch{i.error({title:"Error",message:"Something went wrong! Please try again.",position:"topRight"})}finally{a.hidden=!0}});n.addEventListener("click",async()=>{l++,n.hidden=!0,a.hidden=!1;try{a.hidden=!1;const o=await y(u,l,h);if(o.hits.length===0){i.info({title:"Info",message:"No results found. Try another search query!",position:"topRight"}),n.hidden=!0;return}g.insertAdjacentHTML("beforeend",m(o.hits)),b.refresh();const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l*h>=f?(i.info({title:"End or collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),n.hidden=!0):n.hidden=!1}catch{i.error({title:"Error",message:"Something went wrong! Please try again.",position:"topRight"})}finally{a.hidden=!0}});
//# sourceMappingURL=index.js.map
