import{a as b,S as w,i as n}from"./assets/vendor-CZY24G29.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const L="48848335-f5abf64d59c2aabc1155fb6ba",q="https://pixabay.com/api/";async function p(o,t=1,a=40){try{return(await b.get(q,{params:{key:L,q:o,Image_type:"photo",orientation:"horisontal",safesearch:!0,page:t,per_page:a}})).data}catch(s){console.error("Sorry, there are no images matching your search query. Please try again!",s)}}function f(o){return o.map(({webformatURL:t,largeImageURL:a,tags:s,likes:e,views:r,comments:c,downloads:m})=>`<div class="photo-card">
                    <a href="${a}" class="gallery-link">
                        <img src="${t}" alt="${s}" loading="lazy" />
                    </a>
                    <div class="info">
                        <p><strong>Likes:</strong> ${e}</p>
                        <p><strong>Views:</strong> ${r}</p>
                        <p><strong>Comments:</strong> ${c}</p>
                        <p><strong>Downloads:</strong> ${m}</p>
                    </div>
                </div>`).join("")}const h=document.querySelector("#search-form"),d=document.querySelector(".gallery"),i=document.querySelector(".load-more");i.style.display="none";let g="",l=1;const u=40;let y=new w(".gallery a");h.addEventListener("submit",async o=>{if(o.preventDefault(),g=o.target.elements.searchQuery.value.trim(),!g){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}l=1,d.innerHTML="",i.hidden=!0;try{const t=await p(g,l,u);if(t.hits.length===0){n.info({title:"Info",message:"No results found. Try another search query!",position:"topRight"});return}d.innerHTML=f(t.hits),y.refresh(),t.hits.length===u&&(i.style.display="block"),h.reset()}catch{n.error({title:"Error",message:"Something went wrong! Please try again.",position:"topRight"})}});i.addEventListener("click",async()=>{l+=1;try{const o=await p(g,l,u);if(o.hits.length===0){i.hidden=!0,n.info({title:"Info",message:"No results found. Try another search query!",position:"topRight"});return}d.insertAdjacentHTML("beforeend",f(o.hits)),y.refresh();const{height:t}=document.querySelector(".gallery a").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),l*u>=o.totalHits&&(i.style.display="none",n.info({title:"End or collection",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{n.error({title:"Error",message:"Something went wrong! Please try again.",position:"topRight"})}});
//# sourceMappingURL=index.js.map
